"""Remove question_id from user_responses

Revision ID: 3aacdfd59ac3
Revises: b00a5c5fbbe1
Create Date: 2025-04-17 11:04:47.820146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aacdfd59ac3'
down_revision = 'b00a5c5fbbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz_questions', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
