"""Remove question_id from user_responses

Revision ID: 3eeed5b8733a
Revises: b74c186f62a0
Create Date: 2025-04-17 12:20:23.516195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eeed5b8733a'
down_revision = 'b74c186f62a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_ID'], ['user_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
