"""Remove question_id from user_responses

Revision ID: 4ef9526d32ea
Revises: f00d8ef9527a
Create Date: 2025-04-16 18:38:45.618973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ef9526d32ea'
down_revision = 'f00d8ef9527a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('badge_ID')

    with op.batch_alter_table('game_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('stage_ID')

    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_constraint('user_responses_ibfk_1', type_='foreignkey')
        batch_op.drop_column('question_id')

    with op.batch_alter_table('user_scenario_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_scenario_progress', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_responses_ibfk_1', 'quiz_questions', ['question_id'], ['id'])

    with op.batch_alter_table('game_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
