"""Updated quiz and response models

Revision ID: 78fd08682b89
Revises: e738da6baf4f
Create Date: 2025-04-16 14:04:29.468093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78fd08682b89'
down_revision = 'e738da6baf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('correct_reason', sa.Text(), nullable=True),
    sa.Column('incorrect_reason', sa.Text(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ai_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_responses',
    sa.Column('response_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scenario_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('IS_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('attempt_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_ID'], ['users.user_ID'], name='ai_responses_ibfk_1'),
    sa.PrimaryKeyConstraint('response_ID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_responses')
    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
