"""Remove question_id from user_responses

Revision ID: b00a5c5fbbe1
Revises: 4ef9526d32ea
Create Date: 2025-04-16 18:46:39.748930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00a5c5fbbe1'
down_revision = '4ef9526d32ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
