"""Remove question_id from user_responses

Revision ID: b74c186f62a0
Revises: 3aacdfd59ac3
Create Date: 2025-04-17 12:06:47.720429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b74c186f62a0'
down_revision = '3aacdfd59ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('number_of_attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('badges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('user_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('badge_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('number_of_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('progress', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_ID'], ['users.user_ID'], name='badges_ibfk_1'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('badge')
    # ### end Alembic commands ###
