"""Updated relationships

Revision ID: f00d8ef9527a
Revises: 78fd08682b89
Create Date: 2025-04-16 14:46:06.322575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00d8ef9527a'
down_revision = '78fd08682b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scenario_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_column('stage')

    op.drop_table('user_scenario_progress')
    # ### end Alembic commands ###
